version: "3.8"

services:
  byt-backend:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: byt-backend
    ports:
      - "5005:5000" # Map backend port 5000 to host
    environment:
      - NODE_ENV=production # Or 'production'
      - PORT=5000
    networks:
      - byt-app-network

networks:
  byt-app-network:
    name: byt-app-network
    driver: bridge
