version: "3.8"

services:
  byt-backend:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: byt-backend
    ports:
      - "5005:5000"
    environment:
      - NODE_ENV=production
      - PORT=5000
      - MONGO_URI=mongodb+srv://zhegazy409:wKaT32GesWjat5QD@cluster0.lvlzblw.mongodb.net/baytalkhyata?retryWrites=true&w=majority&appName=Cluster0
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - mongo
      - redis
    networks:
      - byt-app-network

  mongo:
    image: mongo:6.0
    container_name: byt-mongo
    ports:
      - "27018:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    networks:
      - byt-app-network
    volumes:
      - mongo-data:/data/db

  redis:
    image: redis:7.2
    container_name: byt-redis
    ports:
      - "6379:6379"
    networks:
      - byt-app-network
    command: ["redis-server", "--appendonly", "yes"]

networks:
  byt-app-network:
    name: byt-app-network
    driver: bridge

volumes:
  mongo-data:
